### ISSUE TITLE
difference between "epd" and "home" releases?

### ISSUE THREAD

**Issue by nottux** [Modificator/E-Ink-Launcher#10]
Sorry for creating a issue for a question but its because I was kicked from telegram group and couldn't any info about it.

**Comment by YixinChenn** [comment]
![image](https://user-images.githubusercontent.com/37407237/99217515-24b0fa80-2813-11eb-9265-849babea3392.png)
There is an expaination in the release note. Incase you cant read Chinese, epd release is for dual screen phones like YotaPhone, home release is for normal devices.
