### ISSUE TITLE
Use `Intent.ACTION_MAIN` when launching an app

### ISSUE THREAD

**Issue by Kazurin-775** [Modificator/E-Ink-Launcher#14]
The current code ([EInkLauncherView.java#L343](https://github.com/Modificator/E-Ink-Launcher/blob/8fbe462679d105c2d360b6530d6578d9e748976b/app/src/main/java/cn/modificator/launcher/widgets/EInkLauncherView.java#L343)) doesn't set an action for the `Intent` that launches an app. The action should be set to `Intent.ACTION_MAIN` for a launching `Intent`:

```java
intent.setAction(Intent.ACTION_MAIN);
```

Or even better, use:

```java
Intent intent = getPackageManager().getLaunchIntentForPackage("com.package.address");
```

If the action is not set, it defaults to `null`, which will break some apps (for example [plateaukao/browser](https://github.com/plateaukao/browser); also see [this issue](https://github.com/plateaukao/browser/issues/51)).

**Comment by Modificator** [comment]
Thanks,I fix it
