### ISSUE TITLE
更新至0.1.5遇到的3个问题

### ISSUE THREAD

**Issue by kupo** [Modificator/E-Ink-Launcher#8]
https://imgur.com/a/qERlgLG
海信A5更新至0.1.5遇到的3个新问题：1.app名过长图标会上移，可以通过缩小字体解决，但是WIFI连接显示文字过长导致缩小到最小还是不行。2.WIFI连接无法显示WIFI名字，设置里选了依旧不行。WIFI和一件锁屏2个切换按钮无法使用。3.网络传书开启后无法显示ftp的端口号。

**Comment by Modificator** [comment]
上移这个，由于布局原因，除了全部设置只显示１行，不然没法解决
WiFi名字，A5 实测，可以的
ftp 端口显示已修复
